name: CI workfow

on:
  push:
    branches: 
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 22
      uses: actions/setup-java@v4
      with:
        java-version: '22'
        distribution: 'temurin'
        cache: maven
    - name: Build and run tests
      run: mvn -B package
  
    - name: Upload Surefire Reports
      if: always()  # Sørg for, at rapporterne uploades, selvom testen fejler
      uses: actions/upload-artifact@v3
      with:
        name: Surefire-Reports
        path: target/surefire-reports
